import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {PageWrapper} from "@/components/GlobalStyledComponents";

import NavBar from "@/components/NavBar/NavBar";

//ABDALLAH: I commented these as it is not our code.
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

      <PageWrapper>{/*Abdallah: Page wrapper is a styled component to contain all the content in. */}


          <NavBar/> {/* Abdallah: To Display NavBar on all pages.*/}
          {children}


      </PageWrapper>

      </body>
    </html>
  );
}
